import type { Facility, FarmerRequest, Lot, Operator, Person } from "../shared/types";

const u = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=75`;

export const DEMO_FARMER_ID = "farmer-meera";
export const DEMO_OPERATOR_ID = "op-sahyadri";


export const farmer: Person = {
  id: DEMO_FARMER_ID,
  name: "Meera Kulkarni",
  farm: "Kulkarni Vineyards",
  village: "Niphad",
  district: "Nashik",
  crops: ["Grapes", "Raisins", "Onions"],
  lat: 20.0797,
  lng: 74.1106,
  photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=MeeraKulkarni&backgroundColor=d7e4d4",
};

export const farmers: Person[] = [
  farmer,
  {
    id: "farmer-devidas",
    name: "Devidas Patil",
    farm: "Patil Organic Farm",
    village: "Lasalgaon",
    district: "Nashik",
    crops: ["Onion", "Pomegranate"],
    lat: 20.142,
    lng: 74.23,
    photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=DevidasPatil&backgroundColor=e4d7c8",
  },
  {
    id: "farmer-anjali",
    name: "Anjali Deshmukh",
    farm: "Deshmukh Orchards",
    village: "Dindori",
    district: "Nashik",
    crops: ["Grapes", "Strawberry"],
    lat: 20.201,
    lng: 73.83,
    photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=AnjaliDeshmukh&backgroundColor=d4e0d8",
  },
  {
    id: "farmer-ramesh",
    name: "Ramesh Pawar",
    farm: "Pawar Farm Estates",
    village: "Pimpalgaon",
    district: "Nashik",
    crops: ["Onion", "Grain", "Raisins"],
    lat: 20.165,
    lng: 73.99,
    photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=RameshPawar&backgroundColor=f0e6d2",
  },
];

export const operators: Operator[] = [
  {
    id: DEMO_OPERATOR_ID,
    name: "Sahyadri Cold Chain",
    contact: "ops@sahyadri-chain.in",
    facilityIds: ["fac-mohadi", "fac-igatpuri", "fac-dindori"],
  },
  {
    id: "op-coldstar",
    name: "ColdStar Nashik",
    contact: "yard@coldstar.in",
    facilityIds: ["fac-midc", "fac-ozar"],
  },
  {
    id: "op-godavari",
    name: "Godavari Cold Chain",
    contact: "desk@godavari-cold.in",
    facilityIds: ["fac-kopargaon", "fac-yeola"],
  },
  {
    id: "op-deccan",
    name: "Deccan Warehousing",
    contact: "hello@deccan-wh.in",
    facilityIds: ["fac-pimpalgaon", "fac-sinnar", "fac-chandwad"],
  },
  {
    id: "op-lasal",
    name: "Lasalgaon Yard Co-op",
    contact: "yard@lasalgaon.coop",
    facilityIds: ["fac-lasalgaon", "fac-manmad"],
  },
];

export const facilities: Facility[] = [
  {
    id: "fac-mohadi",
    name: "Sahyadri Packhouse",
    operatorId: DEMO_OPERATOR_ID,
    operator: "Sahyadri Cold Chain",
    kind: "packhouse",
    lat: 20.0194,
    lng: 73.8702,
    address: "Mohadi Road, near grape collection shed",
    city: "Mohadi",
    capacityTons: 86,
    baseOccupiedTons: 41,
    ratePerTonDay: 18,
    tempRange: "0 to 2 C",
    crops: ["Grapes", "Pomegranate"],
    photo: u("photo-1537640538966-79f369143f8f"),
    hours: "Open 5:00 to 22:00",
  },
  {
    id: "fac-midc",
    name: "ColdStar Nashik MIDC",
    operatorId: "op-coldstar",
    operator: "ColdStar Nashik",
    kind: "cold",
    lat: 19.9912,
    lng: 73.7874,
    address: "Plot 14, Satpur MIDC",
    city: "Nashik",
    capacityTons: 120,
    baseOccupiedTons: 64,
    ratePerTonDay: 22,
    tempRange: "-2 to 4 C",
    crops: ["Grapes", "Tomato", "Pomegranate"],
    photo: u("photo-1586528116311-ad8dd3c8310d"),
    hours: "Open all day",
  },
  {
    id: "fac-kopargaon",
    name: "Godavari Cold Chain",
    operatorId: "op-godavari",
    operator: "Godavari Cold Chain",
    kind: "cold",
    lat: 19.8854,
    lng: 74.4761,
    address: "Ahmednagar Road, Kopargaon",
    city: "Kopargaon",
    capacityTons: 70,
    baseOccupiedTons: 70,
    ratePerTonDay: 16,
    tempRange: "0 to 5 C",
    crops: ["Sugarcane jaggery", "Onion"],
    photo: u("photo-1587293852726-70cdb56c2866"),
    hours: "Open 6:00 to 21:00",
  },
  {
    id: "fac-lasalgaon",
    name: "Lasalgaon Onion Yard",
    operatorId: "op-lasal",
    operator: "Lasalgaon Yard Co-op",
    kind: "dry",
    lat: 20.1426,
    lng: 74.2326,
    address: "APMC yard, Lasalgaon",
    city: "Lasalgaon",
    capacityTons: 240,
    baseOccupiedTons: 240,
    ratePerTonDay: 9,
    crops: ["Onion"],
    photo: u("photo-1518977676601-b53f82aba655", 1200),
    hours: "Open 6:00 to 19:00",
  },
  {
    id: "fac-pimpalgaon",
    name: "Deccan Dry Store",
    operatorId: "op-deccan",
    operator: "Deccan Warehousing",
    kind: "dry",
    lat: 20.1648,
    lng: 73.9921,
    address: "Pimpalgaon Baswant bypass",
    city: "Pimpalgaon",
    capacityTons: 54,
    baseOccupiedTons: 0,
    ratePerTonDay: 11,
    crops: ["Onion", "Raisins", "Grain"],
    photo: u("photo-1464226184884-fa280b87c399"),
    hours: "Open 7:00 to 20:00",
  },
  {
    id: "fac-igatpuri",
    name: "Igatpuri Hill Cold",
    operatorId: DEMO_OPERATOR_ID,
    operator: "Sahyadri Cold Chain",
    kind: "cold",
    lat: 19.6957,
    lng: 73.5626,
    address: "Ghoti Road, Igatpuri ghat",
    city: "Igatpuri",
    capacityTons: 38,
    baseOccupiedTons: 4,
    ratePerTonDay: 24,
    tempRange: "2 to 6 C",
    crops: ["Grapes", "Strawberry"],
    photo: u("photo-1574943320219-553eb213f72d"),
    hours: "Open 6:00 to 20:00",
  },
  {
    id: "fac-manmad",
    name: "Manmad Junction Store",
    operatorId: "op-lasal",
    operator: "Lasalgaon Yard Co-op",
    kind: "dry",
    lat: 20.2515,
    lng: 74.4381,
    address: "Near railway goods siding",
    city: "Manmad",
    capacityTons: 96,
    baseOccupiedTons: 28,
    ratePerTonDay: 10,
    crops: ["Onion", "Raisins", "Grain"],
    photo: u("photo-1625246333195-78d9c38ad449"),
    hours: "Open 5:30 to 21:00",
  },
  {
    id: "fac-sinnar",
    name: "Sinnar Agri Hub",
    operatorId: "op-deccan",
    operator: "Deccan Warehousing",
    kind: "packhouse",
    lat: 19.849,
    lng: 74.0009,
    address: "Sinnar-Shirdi highway, km 6",
    city: "Sinnar",
    capacityTons: 62,
    baseOccupiedTons: 19,
    ratePerTonDay: 14,
    tempRange: "4 to 8 C",
    crops: ["Tomato", "Grapes"],
    photo: u("photo-1500595046743-cd271d694d30"),
    hours: "Open 6:00 to 22:00",
  },
  {
    id: "fac-ozar",
    name: "Ozar Airfield Cold",
    operatorId: "op-coldstar",
    operator: "ColdStar Nashik",
    kind: "cold",
    lat: 20.0947,
    lng: 73.928,
    address: "Airfield road, Ozar",
    city: "Ozar",
    capacityTons: 48,
    baseOccupiedTons: 12,
    ratePerTonDay: 21,
    tempRange: "-1 to 3 C",
    crops: ["Grapes", "Pomegranate"],
    photo: u("photo-1510812431401-41d2bd2722f3"),
    hours: "Open all day",
  },
  {
    id: "fac-yeola",
    name: "Yeola Grain Bank",
    operatorId: "op-godavari",
    operator: "Godavari Cold Chain",
    kind: "dry",
    lat: 20.0426,
    lng: 74.489,
    address: "Paithan road, Yeola",
    city: "Yeola",
    capacityTons: 110,
    baseOccupiedTons: 110,
    ratePerTonDay: 8,
    crops: ["Grain", "Onion"],
    photo: u("photo-1625246333195-78d9c38ad449", 1200),
    hours: "Open 7:00 to 19:00",
  },
  {
    id: "fac-chandwad",
    name: "Chandwad Crate Yard",
    operatorId: "op-deccan",
    operator: "Deccan Warehousing",
    kind: "dry",
    lat: 20.3293,
    lng: 74.2446,
    address: "Malegaon road, Chandwad",
    city: "Chandwad",
    capacityTons: 44,
    baseOccupiedTons: 0,
    ratePerTonDay: 9,
    crops: ["Onion", "Grain"],
    photo: u("photo-1464226184884-fa280b87c399", 1200),
    hours: "Open 7:00 to 20:00",
  },
  {
    id: "fac-dindori",
    name: "Dindori Grape Cellar",
    operatorId: DEMO_OPERATOR_ID,
    operator: "Sahyadri Cold Chain",
    kind: "cold",
    lat: 20.2045,
    lng: 73.8294,
    address: "Vani road, Dindori",
    city: "Dindori",
    capacityTons: 52,
    baseOccupiedTons: 18,
    ratePerTonDay: 19,
    tempRange: "0 to 2 C",
    crops: ["Grapes"],
    photo: u("photo-1596591877040-96ce140e1f66"),
    hours: "Open 5:00 to 21:00",
  },
];

export const lots: Lot[] = [
  {
    id: "lot-1",
    facilityId: "fac-mohadi",
    farmerId: DEMO_FARMER_ID,
    crop: "Grapes",
    variety: "Thompson Seedless",
    tons: 6.2,
    storedAt: "2026-08-12",
    until: "2026-09-08",
    status: "stored",
  },
  {
    id: "lot-2",
    facilityId: "fac-dindori",
    farmerId: DEMO_FARMER_ID,
    crop: "Grapes",
    variety: "Sharad Seedless",
    tons: 8.4,
    storedAt: "2026-08-18",
    until: "2026-09-14",
    status: "stored",
  },
  {
    id: "lot-3",
    facilityId: "fac-manmad",
    farmerId: DEMO_FARMER_ID,
    crop: "Raisins",
    variety: "Dried Thompson",
    tons: 3.8,
    storedAt: "2026-08-04",
    until: "2026-10-02",
    status: "stored",
  },
  {
    id: "lot-4",
    facilityId: "fac-ozar",
    farmerId: DEMO_FARMER_ID,
    crop: "Grapes",
    variety: "Flame Seedless",
    tons: 4.1,
    storedAt: "2026-08-24",
    until: "2026-09-20",
    status: "inbound",
  },
];

export const voices = [
  {
    quote: "I used to drive to three yards before finding a bay. Now I see the empty ones before the tractor leaves the farm.",
    name: "Ramesh Pawar",
    role: "Onion grower, Lasalgaon",
    photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=RameshPawar&backgroundColor=e4d7c8",
  },
  {
    quote: "The amber pins are my grapes. I check them the way I used to check the vines.",
    name: "Anjali Deshmukh",
    role: "Pomegranate, Solapur road",
    photo: "https://api.dicebear.com/9.x/lorelei/svg?seed=AnjaliDeshmukh&backgroundColor=d4e0d8",
  },
];

export const KIND_LABEL: Record<Facility["kind"], string> = {
  cold: "Cold room",
  dry: "Dry yard",
  packhouse: "Packhouse",
};

export const farmerRequests: FarmerRequest[] = [
  {
    id: "req-devidas-1",
    farmerId: "farmer-devidas",
    farmerName: "Devidas Patil",
    farmerVillage: "Lasalgaon",
    farmerContact: "+91 98220 54321",
    crop: "Onion",
    variety: "Red Nashik",
    tons: 12,
    days: 45,
    lat: 20.142,
    lng: 74.23,
    requestedAt: "2026-08-25",
    status: "pending",
  },
  {
    id: "req-anjali-1",
    farmerId: "farmer-anjali",
    farmerName: "Anjali Deshmukh",
    farmerVillage: "Dindori",
    farmerContact: "+91 98223 99887",
    crop: "Grapes",
    variety: "Thompson Seedless",
    tons: 7.5,
    days: 25,
    lat: 20.201,
    lng: 73.83,
    requestedAt: "2026-08-26",
    status: "pending",
  },
  {
    id: "req-ramesh-1",
    farmerId: "farmer-ramesh",
    farmerName: "Ramesh Pawar",
    farmerVillage: "Pimpalgaon",
    farmerContact: "+91 98221 11223",
    crop: "Tomato",
    variety: "Hybrid Red",
    tons: 5,
    days: 14,
    lat: 20.165,
    lng: 73.99,
    requestedAt: "2026-08-26",
    status: "pending",
  },
];

